### ISSUE TITLE
problem on environment.yml

### ISSUE THREAD

**Issue by Freecheck100** [LechengKong/OneForAll#10]
When I run the command "conda env create -f environment.yml", there is a problem: Could not find a version that satisfies the requirement en-core-web-sm==3.5.0.
![微信图片_20240329110119](https://github.com/LechengKong/OneForAll/assets/121811600/150388f6-bbb8-4e24-81a5-d1b4a3621a1d)

**Comment by LechengKong** [comment]
Hi, I'll try reproduce this. Meanwhile, if the rest of the packages are installed, you can do `python -m spacy download en_core_web_sm` to download en-core-web-sm from spacy, and see if the code runs.

**Comment by Freecheck100** [comment]
Maybe the problem is that I didn't install spacy. After installing spacy, the problem solved.
