### ISSUE TITLE
Replicating the results of Table12 

### ISSUE THREAD

**Issue by StephenK1998** [LechengKong/OneForAll#12]
Hi! Thanks for your brilliant work! I'm pretty interested in the results of Table 12 in the appendix. I wonder if there are any configs for us to replicate the results of Table 12? Thank you.

**Comment by LechengKong** [comment]
Hi @StephenK1998 ,

Sorry for the late reply. We just pushed an updated version, and there is no direct config to replicate table 12, but the model we use for the ablation study is [here](https://github.com/LechengKong/OneForAll/blob/2923c11d126853ca9438d50017a6a747eda5fa46/models/model.py#L41). You can use this model and create a dataset without prompt nodes to replicate if you are in a hurry. I will implement a side code for replication later.

**Comment by StephenK1998** [comment]
Thanks for your reply! I will check the model and write relevant codes
