### ISSUE TITLE
For the node type

### ISSUE THREAD

**Issue by ChirsHuanhuan** [LechengKong/OneForAll#13]
Hi! Thanks for your brilliant work! There are some parts in the code that I am confused about, I hope you can help me answer them!
What is the logic node I found in the data processing of the ARXIV dataset? This does not seem to appear in the paper. At the same time, why is the Noi node text not seen in FB15K237_fs? Hope you can get the answer, thank you! !

**Comment by LechengKong** [comment]
Hi @ChirsHuanhuan ,

Sorry for the late reply. Yes, logic_node is for an offline task we did that was not included in the paper. Can you be more specific about the noi node text problem for FB15K237? Can you provide pointers to the code snippet? Thanks!
