### ISSUE TITLE
About zero shot task

### ISSUE THREAD

**Issue by W-rudder** [LechengKong/OneForAll#17]
I think this is a fantastic work! And it's been incredibly interesting for me!
However, I have a question that I'd like to trouble you with. I'm curious about the transferability of the model, for instance, training the model on the training set from arXiv in a supervised learning setup, and then testing it on the test sets from PubMed and Cora. Can the existing code achieve this? Specifically, how should I modify the configuration file? Looking forward to your reply! Wishing you smooth work and a happy life!

**Comment by W-rudder** [comment]
Is this the correct way to modify it?
For`config/task_config.yaml`

```python
arxiv_transfer: &arxiv_transfer
  <<: *E2E-node
  dataset: arxiv
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: arxiv
    - stage: valid
      split_name: valid
      dataset: arxiv
    - stage: test
      split_name: test
      dataset: arxiv
    - stage: test
      split_name: test
      dataset: pubmed_node
    - stage: test
      split_name: test
      dataset: cora_node

**Comment by LechengKong** [comment]
Hi @W-rudder , yes, this is the right config.

**Comment by W-rudder** [comment]
> Hi @W-rudder , yes, this is the right config.

Thanks for your reply! I learned a lot from your paper and codes. Best wishes to you^_^
