### ISSUE TITLE
molecular graph data problem?

### ISSUE THREAD

**Issue by studylyc** [LechengKong/OneForAll#20]
Hello, how can I use the HIV molecular graph, first download the data, and then perform data read operations. Download is not allowed due to network problems. Thanks.

**Comment by studylyc** [comment]
data = load_dataset("haitengzhao/molecule_property_instruction", cache_dir=cache_dir, split=NAME_TO_SPLIT[name], ) is not allowed due to network problems.

**Comment by LechengKong** [comment]
Hi @studylyc , I think in some region, huggingface is blocked. You can manually download the dataset using VPN, and copy the huggingface cache of your local machine. However, the easiest solution is  to setup [hf-mirror](https://hf-mirror.com/) for your machine (instruction provided in their site), which will let download pretty much anything from huggingface (you don't need to change any of our code.).
