### ISSUE TITLE
Inquiry about Cora data

### ISSUE THREAD

**Issue by jujulili888** [LechengKong/OneForAll#21]
Hi, thanks for your excellent work, and it inspires a lot! Here I have a question about the Cora dataset in your work that the cora.pt is a newly-organized cora TAG developed by you own, the order of nodes in it is not consistent with the official dataset provided by PyG, may I ask if you still keep the correspondence between each node and paper id for cora.pt? Thx!

**Comment by LechengKong** [comment]
Hi @jujulili888 ,
Thank you for your interest in our work. We are glad that our work helps with your research.
For the cora dataset, we obtain it from [this work](https://github.com/CurryTang/Graph-LLM). According to this [issue](https://github.com/CurryTang/Graph-LLM/issues/7#issuecomment-1821416801), I think it is not possible to align the indices, without having the code used to generate the pyg cora dataset. Unfortunately, we do not have any good solution to this as well.
