### ISSUE TITLE
dataset format

### ISSUE THREAD

**Issue by AMark-CS** [LechengKong/OneForAll#22]
Hi, what a great work! I truly like the structure you put forward. However, when I follow the instructions given in the README to add my own datasets such as citeseer, I encountered with the following problems:
![image](https://github.com/user-attachments/assets/64c51d9b-7d5a-41a8-a3e6-ae52510bfd8f)
As you can see, the data structure in the folder Cora and the Citeseer are not the same, leading to the problem of missing important attributes needed for the training session.(Plus: the Citeseer dataset is loaded using the pyg)
So I'm wondering if it is because of the dataloader(I guess the dataloader I used might be different from the one you used) or if it is a must that we implement the categories.csv and add the attributes all by ourselves?
I would appreciate it if you could reply!

**Comment by LechengKong** [comment]
Hi @AMark-CS ,

Sorry for the late reply. We got the cora.pth from [here](https://github.com/CurryTang/Graph-LLM) and not from pyg. Pyg's version does not contain raw text about abstracts and titles. They have script to collect cora raw text. I don't think they have citeseer provided, and I think if you want to add citeseer, you will need to collect raw text for citeseer yourself.

Hope this helps.

**Comment by AMark-CS** [comment]
Thank you for sparing your precious time to reply!
Your suggestion perfectly solved my problem and I think improved my coding skills as well^_^, many thanks for that!
In addition, when I was wandering around github I found something that might tackle the citeseer issue and help those who has the same prob as me: [GLBench](https://github.com/NineAbyss/GLBench)
![image](https://github.com/user-attachments/assets/f21ac951-24ba-4b74-acc7-6b60670671be)
It implemented the citeseer dataset in ofa, which I think is also a great work.
